controllers:
    resource: ../src/Controller/
    type: attribute

github_score:
    path: api/v1/score
    controller: App\Controller\GithubController::score
    methods: GET

github_login:
    path: api/v1/index
    controller: App\Controller\GithubController::index
    methods: GET


