controllers:
    resource: ../src/Controller/
    type: attribute

github_score:
    path: api/v1/score
    controller: App\Controller\GithubController::score
    methods: GET

github_score_update:
    path: api/v1/update
    controller: App\Controller\GithubController::update
    methods: PUT

