version: '3'

services:
  database:
    container_name: database
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
    volumes:
      - './mysql:/var/lib/mysql'
    ports:
      - '3306:3306'

  nginx:
    platform: amd64
    container_name: nginx
    working_dir: /app
    image: nginx:latest
    hostname: localhost
    command: [nginx-debug, '-g', 'daemon off;']
    environment:
      - NGINX_HOST=127.0.0.1
      - NGINX_PORT=80
    ports:
      - '8080:80'
    volumes:
      - './:/app'
      - './nginx/conf.d:/etc/nginx/conf.d'
    depends_on:
      - database
      - php

  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - './:/app'
    depends_on:
      - database

  composer:
    restart: "no"
    container_name: composer
    image: library/composer:latest
    command: install
    working_dir: /app
    volumes:
    - './:/app'



